set(KMPKG_TARGET_ARCHITECTURE x64)
set(KMPKG_CRT_LINKAGE dynamic)
set(KMPKG_LIBRARY_LINKAGE static)

set(KMPKG_CMAKE_SYSTEM_NAME Darwin)
set(KMPKG_OSX_ARCHITECTURES x86_64)
set(KMPKG_BUILD_TYPE release)
