set(KMPKG_TARGET_ARCHITECTURE x64)
set(KMPKG_CRT_LINKAGE dynamic)
set(KMPKG_LIBRARY_LINKAGE dynamic)
set(KMPKG_ENV_PASSTHROUGH PATH)

set(KMPKG_CMAKE_SYSTEM_NAME MinGW)
set(KMPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
