set(KMPKG_POLICY_EMPTY_PACKAGE enabled)

if(CMAKE_HOST_WIN32 AND KMPKG_CMAKE_SYSTEM_NAME AND NOT KMPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" AND NOT KMPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW")
    return()
endif()
